### ISSUE TITLE
The app keeping the user loggedIn!

### ISSUE THREAD

**Issue by atefhares** [openMF/self-service-app#115]
**Summary:**

The app is saving that I am logged In after closing it.

**Steps to reproduce:**

login with username & pass and simply close that app then open it again and you will see the login screen.

**Expected behavior:**

App should keeps user logged in!

**Observed behavior:**

The login screen.

**Device and Android version:**

Android 6.0.1

**Comment by Pritom14** [comment]
Since the app deals with money transactions , so it's better that it is logged out once the app is closed, don't you think? What's your opinion?

**Comment by therajanmaurya** [comment]
@atefhares @Pritom14  is right.

**Comment by atefhares** [comment]
@Pritom14 @therajanmaurya  I am convinced of your idea but that is a poor UX, is n't there any other possible way to handle this?!
At least offer to keep the user logged In after checking that there is a pin/password/pattern on the device's lock screen and otherwise don't keep him

**Comment by shivamarora96** [comment]
@atefhares @therajanmaurya @Pritom14 
I think Login details(username and Password) should be asked only one time.After successful login, app should prompt the user to set the security code (Numeric generally). After this whenever user reopened the app it should only ask for the security code (Like Dropbox, BOB mpassbook) instead of re-typing the username and password again and again.Whenever a user logged out everything would be reset. 


![screenshot_2017-03-05-00-18-50-502_in co bankofbaroda mpassbook](https://cloud.githubusercontent.com/assets/20308009/23581444/ec92ec66-0139-11e7-85d1-1fad3e698e5c.png)

**Comment by therajanmaurya** [comment]
further discussion here #132
