### ISSUE TITLE
Loan repayment Activity

### ISSUE THREAD

**Issue by HilaryKinyua** [openMF/self-service-app#1334]
I want some help from mifos developers. Am trying to customize my mifos mobile to meet my needs and would want a user to click a button that takes him or her to Repay Loan section or activity, how do I go about this? Please, someone, help

**Comment by devansh-299** [comment]
Hi @HilaryKinyua , Mifos Mobile does support this functionality. But recently because of a certain change being merged, users are not able to interact with loan account items in the recycler view.
I would suggest you to make the following change so that you can undo same 

* In Android Studio go to `build.gradle` at Project level
* Change `supportLibraryVersion = '1.1.0'` to `supportLibraryVersion = '1.0.0'`

**Comment by jawidMuhammadi** [comment]
Thanks @devansh-299 . I was facing the same issue (loan account items were not being clicked). After doing changes in `build.gradle` now it is working.

**Comment by HilaryKinyua** [comment]
Thank you for this
