### ISSUE TITLE
TableView width in Repayment Schedule fragment.

### ISSUE THREAD

**Issue by jawidMuhammadi** [openMF/self-service-app#1354]
**Summary:**

TableView width is not covering all the space in **larger devices** or when the app is in the **landscape** mode which is supposed to do.

**Steps to reproduce:**

- Go to accounts -> Loan tab
- Select any disbursed loan
- Tap on Repayment Schedule

**Expected behaviour:**

Table View width should cover all the space.

**Device and Android version:**

Pixel 3, API 29
Android Version 10 (Q)
Emulator

**Screenshots:**
![Screenshot_1581763081](https://user-images.githubusercontent.com/49963168/74586710-6b698e00-5010-11ea-94c7-3705c0c675e9.png)
![Screenshot_1581763090](https://user-images.githubusercontent.com/49963168/74586713-715f6f00-5010-11ea-9c12-c450155aebcd.png)

**Comment by jawidMuhammadi** [comment]
I am going to work on it

**Comment by jawidMuhammadi** [comment]
Before working on this issue, please take a look at the linked closed PR

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi, I want to take this up. 
I researched a bit on the surface and if I try to reproduce this, the app crashes due to java.lang.IndexOutOfBoundsException. I'll look at it in details and will come up with a solution.

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi, I was investigating why the app crashed while I was replicating, "Steps To Reproduce" and I realised that was because the View that was being inflated lacked the necessary "layout_width" attribute. Due to that when someone will go to accounts -> loans tab -> select any disbursed loan -> repayment schedule, the app crashed!!

Here's the video : 

https://user-images.githubusercontent.com/59947871/230666763-6fff9c94-5836-4305-8ea7-74188c905f84.mp4
