### ISSUE TITLE
Potential security problem

### ISSUE THREAD

**Issue by intrigus-lgtm** [openMF/self-service-app#1556]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential security problem.

Pinging @vorburger as I've reported a similar instance in fineract.

**Comment by vorburger** [comment]
@edcable could you ping any active mifos-mobile maintainers here to engage with @intrigus-lgtm ?

**Comment by edcable** [comment]
@miPlodder can you please reach out to @intrigus-lgtm?

**Comment by miPlodder** [comment]
@intrigus-lgtm @edcable We use the mailing list for this purpose.

**Comment by miPlodder** [comment]
@intrigus-lgtm We can use the Mifos Mailing list for communication or a private mail thread for the purpose.

@edcable Can you create a Security Advisory and add req folks as collaborators?

**Comment by vorburger** [comment]
@miPlodder I've created https://github.com/openMF/mifos-mobile/security/advisories/GHSA-9657-33wf-rmvx

FYI security sensitive matters are typically not discussed on public mailing lists until they are resolved. 

I don't know much about these GitHub security advisories, but they seem like a good way to deal with this. I assume after everything is fixed, they may become public when the (now fixed) vulnerability will be "disclosed" in the future.

I won't be able to directly support this effort (just due to lack of time) - best of luck!

**Comment by miPlodder** [comment]
Thanks @vorburger ,

@intrigus-lgtm Security Advisory is created, https://github.com/openMF/mifos-mobile/security/advisories/GHSA-9657-33wf-rmvx

**Comment by intrigus-lgtm** [comment]
Fixed, see https://github.com/openMF/mifos-mobile/security/advisories/GHSA-9657-33wf-rmvx
