### ISSUE TITLE
User is logged out after clicking on the cancel button

### ISSUE THREAD

**Issue by PratyushSingh07** [openMF/self-service-app#2105]
**Summary:**
After clicking on the cancel button in the passcode page and then pressing back on the screen , the user is sent to the login page 

**Steps to reproduce:**
- select the `Forgot Passcode, Login Manually` in the passcode page
- click on `cancel` when the dialogue box appears
- now back press on the screen 

**Expected behaviour:**
- after back press and then opening the app , the application should have started from the passcode page and not from the login activity

**Observed behaviour:**

https://user-images.githubusercontent.com/90026952/230833578-63c51cc4-18cf-40ba-b80d-e55973704c42.mp4

**Device and Android version:**

Device: Samsung M11
Android: 11

**Comment by PratyushSingh07** [comment]
I will work on this

**Comment by vyukti13** [comment]
Hi @PratyushSingh07  I think this issue is also solved with #2104 Unable to login after clicking on the cancel button. 
I have raised a PR for the same fix-#2104-Unable-to-login-after-clicking-on-the-cancel-button #2232 . When I am running the app after the following changes, things are working fine. 
Please check it once

**Comment by ayush290104** [comment]
@vyukti this issue still persists. was your PR merged.

**Comment by ayush290104** [comment]
@PratyushSingh07 in this issue after clicking cancel if we enter the correct passcode it says not valid

**Comment by ayush290104** [comment]
@jawidMuhammadi  If I go to the implementation of this function it takes me to a read only file. I guess the problem lies when we click on forgot passcode it logs out the user then and there only but it should do only when user clicks okay.
Can you please guide me 
![Screenshot (35)](https://github.com/openMF/mifos-mobile/assets/116818222/abc0bb6b-313d-4ecc-9d96-08c32bdacaec)

**Comment by PratyushSingh07** [comment]
> @PratyushSingh07 in this issue after clicking cancel if we enter the correct passcode it says not valid

please see issue #2104

**Comment by vyukti13** [comment]
@ayush290104 No my PR is not yet merged, but this issue will be resolved with that PR

**Comment by ayush290104** [comment]
@vyukti13 does your pr solve issue #2259?

**Comment by vyukti13** [comment]
Yes @ayush290104 , it is

**Comment by PratyushSingh07** [comment]
> Hi @PratyushSingh07 I think this issue is also solved with #2104 Unable to login after clicking on the cancel button. I have raised a PR for the same fix-#2104-Unable-to-login-after-clicking-on-the-cancel-button #2232 . When I am running the app after the following changes, things are working fine. Please check it once

@vyukti13 your PR didn't solve this issue

**Comment by PratyushSingh07** [comment]
@ayush290104 & @vyukti13 we now cannot replicate this exact issue in our app. The new issue doesn't let you exit if you click on cancel button on passcode activity. And for that reason I am closing this issue . I will open another issue (that describes the current state ) and maybe one of you can fix this as the solution is relatively simple than the rest of the issues.
