### ISSUE TITLE
Filter option in Accounts.

### ISSUE THREAD

**Issue by ayush290104** [openMF/self-service-app#2184]
**Summary:**

While clicking on filters it shows no account found

**Steps to reproduce:**

After loging in click on accounts.
Then select the filter tab,
 dont select any option and click on filter.

**Expected behaviour:**
Ideally it should show all the accounts if no filter is selected.

What did you see instead?  Describe your issue in detail here.
It is showing no accounts found.
**Device and Android version:**

I am using android 13 on Iqoo z3 and it is stock rom by company.

**Screenshots:**

https://github.com/openMF/mifos-mobile/assets/116818222/1935d849-305a-4aa9-94bb-7586dfdc79b3

**Comment by ayush290104** [comment]
I have seen the problem and quite solved it on my local system. I would like to share if anyone reviews it.

**Comment by PratyushSingh07** [comment]
hey @ayush290104 this issue is already open check https://github.com/openMF/mifos-mobile/issues/1397 
I am glad that you have solved it , you  can open a PR and make sure to link https://github.com/openMF/mifos-mobile/issues/1397 to the PR that you make and kindly close this issue as this is redundant

**Comment by PratyushSingh07** [comment]
can you please close down this issue !!
