### ISSUE TITLE
Currency changes while selecting a Loan Product.

### ISSUE THREAD

**Issue by AbhilashG001** [openMF/self-service-app#224]
**Summary:**

Currency changes while selecting a Loan Product. The currency should be what the user selects it to be and not change with the Loan Product selected.

**Steps to reproduce:**

Step 1) Open the self service app.
Step 2) Select the Loan tab in home screen.
Step 3) Tap on the menu anchored to the overflow button at the top-right corner and select "Apply for Loan".
Step 4) Select a Loan Product.

**Expected behavior:**

The currency shouldn't change according to the loan product selected.

**Observed behavior:**

The currency changes on selecting different Loan Products from the list.

**Device and Android version:**

Device : Motorola Moto G 1st Generation [XT1033] [Falcon]
ROM : CyanogenMod 13.0 Snapshot build

**GIF:**

![videotogif_2017 03 22_09 52 28](https://cloud.githubusercontent.com/assets/20839661/24182255/91717e1e-0ee6-11e7-9a18-8f7127fdefe4.gif)

**Comment by AbhilashG001** [comment]
I would like to work on this issue.

**Comment by santoshconflux** [comment]
@AbhilashG97 , The currencies are unique to loan products and charges & the desired currencies are added to loan product/charge  while creating them. Even in Web application of Mifos, you cannot  change currency in loan application or  for charges. 

I think its expected behaviour, not an issue. @therajanmaurya
