### ISSUE TITLE
Fix: Every Time Login. 

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#27]
Whenever we open the app, the user needs to log in and enter the credentials again and again. 

**Expected**
User has to log in one time and rest of time, he able to see his accounts and other staff.

**Comment by therajanmaurya** [comment]
@ishan1604 I found that Login Presenter is working the PrefrenceHelper.
That is not right according to MVP pattern. 

Need a quick discussion about the future fixes.

**Comment by ishan1604** [comment]
@therajanmaurya 

MVP Pattern doesn't define user experience and/or User Flow.

Now coming on to, why Login is necessary every time? Since this app involves financial transactions I wouldn't want to allow any chance of my financial data or money being stolen.

Imagine you signed into your app, and give your phone to someone to make a call. After the call I see the app running in background, I can quickly go in and start peeking at your personal financial data. :) 

If you are satisfied with the answer please close this Issue.

**Comment by therajanmaurya** [comment]
So you mean, User need to log in every time, whenever he/she will open the app.

**Comment by ishan1604** [comment]
Yes

**Comment by therajanmaurya** [comment]
Ok.

**Comment by Nayan** [comment]
Or think of situation where you have lost the mobile and person having
access to mobile will have access to your bank account too

**Comment by therajanmaurya** [comment]
One more thing, right now when user is logging in to app, He is able to look list of clients,
and there is a single client as the user is only one.
is it good? or he is able to look his account directly with seeing the client list.
