### ISSUE TITLE
'Account Overview' on home page leading nowhere

### ISSUE THREAD

**Issue by santoshconflux** [openMF/self-service-app#458]
@therajanmaurya , I think you might have plan for enhancements for this. May I know what it is?

**Comment by therajanmaurya** [comment]
Yes, This feature will show total loan and savings account balance, If you have any suggestion about that other thing we can show, suggest.

Yes, I have planned for this feature, I will make it very soon and let you know.

**Comment by therajanmaurya** [comment]
@santoshmath Here is the mock-up for the account overview.
![image](https://user-images.githubusercontent.com/5724482/31578555-385a74ae-b141-11e7-8b70-e617e3983a06.png)

**Comment by dilpreet2028** [comment]
Hey @therajanmaurya , the mockup looks great but instead of showing these on a completely new page, shouldn't we show them on the main screen only so that user doesn't have to go to another page for just getting an overview. 

@denilap gave a feedback regarding the surveys that as it is not a primary feature for the app so that could be placed in the navigation drawer, so after that we can move Recent Transaction to Surveys location and this way there will have enough space for showing account overview on the top only.

**Comment by therajanmaurya** [comment]
First, Please update your build, I changed lot's of thing and second I have played the previous UI in which we were showing the account overview that is making a bad impact on UX perspective. It was made Home screen lazy and somehow user has to wait time that account overview will be loaded.

I checked many many apps of banks they don't show balance or account overview on home because of security reasons. I choose to remove it even if you check Paypal had the same thing and they removed this feature and showing on the other activity.

And about the Surveys, If we will remove, It will not give us space to fit in something Horizontally if you think according to design.

**Comment by santoshconflux** [comment]
@therajanmaurya , It looks good. I think there are no share accounts for the  client. That's why it's not displaying. 

As you have seen in Web app of self service, the following things needs  to be displayed in mobile app as well:

1. Number of Loan Accounts
2. Number of Savings Accounts
3. Number of Share Accounts.
4. Total Amount in Arrears mentioning respective loan accounts (much needed as sometimes client fails to make repayments on scheduled date and when he checks self-service app, his first priority will be  to make repayment for arrears )

I agree with @dilpreet96 , as it's dashboard data , all these details need to be displayed on home  screen.
