### ISSUE TITLE
User Story -  Register/Sign-up

### ISSUE THREAD

**Issue by denilap** [openMF/self-service-app#56]
User Story: As a customer opening the self-service app, I want to see an option to either login or register, so I can  access my self-service online account
### **Implementation of Registering a self service user : https://github.com/openMF/self-service-app/issues/56#issuecomment-309098971**
Acceptance Criteria-

- [x]  User should see login screen with input data fields for 1) Username 2) Password 
- [ ] User should see an option to Register/Sign-up if they don't have an online self-service account created - clicking on this option will route user to the Registration/Sign-in screen
- [ ] User should be shown an option to reset password through 'Forgot Password' link - clicking on this should route the user to the Reset Password screen
- [ ] User should be shown the support number/contact information of the financial institution on the splash screen

**Comment by therajanmaurya** [comment]
- [x] User should see login screen with input data fields for 
- Username
- Password
  ![login](https://cloud.githubusercontent.com/assets/5724482/19969114/58129d16-a1fd-11e6-8c6a-d6c496566312.jpg)
  This feature implemented successfully and working fine.

**Comment by therajanmaurya** [comment]
- [ ] User should see an option to **Register/Sign-up**.
  if they don't have an online self-service account created - clicking on this option will route user to the Registration/Sign-in screen.
- Login Approach :  As we logging into the app. login screen prompt the username and password of the user and the client,  who is logging into that are attached to that user.

this is the whole approach we are doing now.

I need some clarification and need some help. How we will take this up Resgister feature.

Question : 
1. We will add the create user feature using the [REST API](https://demo.openmf.org/api-docs/apiLive.htm#users_create) with the data

``` json
{
    "username": "newuser",
    "firstname": "Test",
    "lastname": "User",
    "email": "whatever@mifos.org",
    "officeId": 1,
    "staffId": 1,
    "roles": [2,3],
    "sendPasswordToEmail": true
}
```

This is fine we can easily get this up.
1. The Whole problem is, 
- How we can attach the client to the user during this approach.
- Is that we have to create a client also, during creating user account.

Please Help @ishan1604, @shrunk7byadagi, @rajuan, @Nayan, @edcable

**Comment by rajuan** [comment]
@ishan1604, @shrunk7byadagi, @rajuan, @Nayan, @edcable , @denilap , @therajanmaurya 

The user creation API that you have mentioned is for a normal user. For a self service user, additional flag of isSelfServiceUser and clients is required. Look at the additional examples given in create user api doc.

Creating a user is a secure operation that needs authentication credentials with appropriate permissions. Register/reset password are done in the context of unauthenticated users. In these cases, you need to have intermediate implementation that validates that authenticity of the user. For eg, things like asking them to provide their DOB, mobile number, loan account number, a transaction info on a associated account etc. Or send an OTP on the registered mobile number Or any other simple or more complex way. The API end point used for such validations are not attached to any user ID/password, but the implementation should be able to use the existing platform client or loan or savings APIs in the background to verify the user input data and identify the client for whom you are going to create self service user credentials. Again once the validation process is complete, use the create user API in the background and create the required user and the associate the identified client to the user. Hope this clarifies.

**Comment by atefhares** [comment]
i want to work on this, is it ready to be implemented?

**Comment by rahulbabbar1** [comment]
@therajanmaurya for the client problem, i think what we can do is:
- Case 1 (When self service user is registering through the app): User can simply register in the app using his mobile no, and email address similar to as other apps do. After successful sign up, user will get an option link/request a client for his account until then we can store a boolean haveClientConnected with a fals value.
- Case 2 (When client registers a new self service user under his/her ): In this scenario since their is no self service user present so the system will create a new user and send the username and password to the self user's mobile no.

If the approach seems right, I would like to work on this.

**Comment by dilpreet96** [comment]
@therajanmaurya @rajuan 
I am able to create a client and associate that client to a newly created self service user .
My question is
While registration do we just have to ask for the client Id and ask for dob, phone no, etc for checking the authenticity of user or we also have to allow the client to create their own client account?

**Comment by dilpreet96** [comment]
@puneetkohli521 @therajanmaurya @rajuan 
##### `Clarification needed`
Creating a self service user links one or more clients with one self service user account.
For creating a self service user I used :-
```
{
    "username": "testabc12",
    "firstname": "Test",
    "lastname": "User",
    "email": "dilpreet2028@gmail.com",
    "officeId": 1,
    "staffId": 1,
    "roles": [2,3],
    "isSelfServiceUser": true,
    "sendPasswordToEmail": false,
    "password": "Test@123",
    "repeatPassword": "Test@123",
    "clients": [1795]
}
```
With this api:- https://demo.openmf.org/fineract-provider/api/v1/users
Along with the `admin token in the request header`.

This means that only an authorised and authenicated person can create a self service user.
#### Android application side (Problem):
Creating a self service user would require a token with admin access within the request header which requires to store the admin credentials within the application which is not a secure way of doing things so is there any other way to proceed further?

For a detailed and pictorial description you can check:- 
https://docs.google.com/document/d/1TUYWX2fFSL-_93b15eB5gfDYCynrmSkOWbi2BlP0NLM/edit?usp=sharing

**Comment by dilpreet2028** [comment]
@therajanmaurya  @puneetkohli521  @droidchef  @edcable 

In order to create a self service user we need an admin token. For this we first need to perform some tasks on Mifos X Client : https://demo.openmf.org/#/  
- **Create a role** with a `CREATE USER` and `CREATE USER CHECKER` (used for verifying the creation of user) permissions only.
- **Create a user(admin)** and assign only the previously created role to it.
Retrieve this admin token and hardcode it in the self service application and this admin token is authorized to perform only 2 task i.e. creating a self service user and verifying it.
#### On Android side:
-  Send a POST request to create a user on this api :- https://demo.openmf.org/fineract-provider/api/v1/users along with the previously fetched token in Header and the required Request Body which returns a Response : 
 ```
{
    "commandId": 11232,
    "resourceId": 123,
    "rollbackTransaction": false
}
 ```
- We need to approve the `Maker Checker Entry` for this particular Audit for which send a POST request to : https://demo.openmf.org/fineract-provider/api/v1/makercheckers/{auditId}?command=approve 
by passing `auditId` as the `commandId` we got during the creation of a self service user.

**Comment by mainaliayush2007** [comment]
I followed the same process mentioned here but i was unable to register a self-service user from the app.
1. I created a admin and gave the role of CREATE USER and CREATE USER CHECKER
2. In order to test the API i used Postman, there i set the Authorization to Basic Auth then sent the POST request to the url https://<domain-name>/fineract-provider/api/v1/users with the headers 
Fineract-Platform-TenantId
username
firstName
lastName
email
mobileNumber
accountNumber
password
authenticationMode

after sending the request i got the response as
{
    "developerMessage": "The JSON provided in the body of the request is invalid or missing.",
    "defaultUserMessage": "The JSON provided in the body of the request is invalid or missing.",
    "userMessageGlobalisationCode": "error.msg.invalid.request.body",
    "parameterName": "id",
    "value": null,
    "args": []
}

Please help me i have been stuck in this point for more than 3 weeks

**Comment by mainaliayush2007** [comment]
I followed the same process mentioned here but i was unable to register a self-service user from the app.

I created a admin and gave the role of CREATE USER and CREATE USER CHECKER
In order to test the API i used Postman, there i set the Authorization to Basic Auth with the username and password of the admin created with permission CREATE USER and CREATE USER CHECKER then sent the POST request to the url https:///fineract-provider/api/v1/users with the header
Fineract-Platform-TenantId

and body 
username
firstName
lastName
email
mobileNumber
accountNumber
password
authenticationMode
after sending the request i got the response as

{

    "timestamp": 1518940691610,

    "status": 415,

    "error": "Unsupported Media Type",

    "message": "Unsupported Media Type"

}

Please help me i have been stuck in this point for more than 3 weeks
