### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by sgatibaru** [openMF/self-service-app#78]
I really need your help on this. Its not bad to ask so please forgive my naivete, Ive been trying to login to the app as a user, i even created a datatable for user authentication called 'authentication' on the demo system. I however cant access the system.. **I also was wondering if a new user could create an account in the system**. Ive been digging around the internet and i tried using the user creation profile on the client-app but there were too many errors created and i totally broke the build. _Please is there a username and password of how do i go about creating a user?_

i tried using _mifos_ and _password_ but there is  an error fetching data

**Comment by therajanmaurya** [comment]
@Siltech here is the credentials 
username: selfservice
password: Password@123

**Comment by sgatibaru** [comment]
Thank you for that @therajanmaurya, is there a way to map this user to mifos? i cant seem to find 'selfservice' on the list of account holders? Or rather, how to create a mifos client who can log into the client service app?

**Comment by edcable** [comment]
@SkylerGatibaru Since the self-service APIs were also designed to support agents authenticating in and servicing multiple clients, there was some initial confusion with assigning a login which only has a one to one relationship with the client. As @therajanmaurya you should just use the demo credentials for attempting to work on these features. We are still building out a way for a user to self-create their credentials via the app which is discussed at https://www.mail-archive.com/dev@fineract.incubator.apache.org/msg01965.html and we're also building out the UI for a back office user to create a self-service user via the web app: https://github.com/openMF/community-app/issues/1820

**Comment by therajanmaurya** [comment]
I think. No Further disscssion needed.

**Comment by sgatibaru** [comment]
Hi Rajan Muaraya, a few things have been keeping me away from work. i
deeply apologize for my quietness and i hope all is well. I just came back
to work and i will have another look at the code..

Also, I've been trying to get around this by building an ionic app, just to
view the savings accounts details and possibly to apply for a loan. I will
push data directly to the database as a start before i get through the api.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
