### ISSUE TITLE
Doesn't change the language under the Setting option

### ISSUE THREAD

**Issue by theamritanair** [openMF/self-service-app#893]
**Summary:**

In the Settings option, on changing the language, there's no change.  
The changes occur only if English and Hindi languages are selected.

**Steps to reproduce:**
1. Open the app. Open the Navigation Drawer.
2. Select the Settings option.
3. Click on Languages.
4. Select the language you want.

**Expected behaviour:**

On selecting the language, the app should change to the selected language.

**Observed behaviour:**

The changes only occur if the English and Hindi languages are selected. For the other languages, no changes occur.

**Device and Android version:**
Model: Redmi Note 4(Mido)
Android Version: Nougat 7.0

**Screenshots:**

![ezgif-mifosmobile](https://user-images.githubusercontent.com/38832512/47209812-ea17d200-d3ae-11e8-8289-ad2f5804dbec.gif)

**Comment by miPlodder** [comment]
@theamritanair This is not a bug. Currently, translations for others languages are given in English only. That's why it's occurring. Check out this French translation [file](https://github.com/openMF/mifos-mobile/blob/development/app/src/main/res/values-fr/strings.xml). 

Only translation for the Hindi language is available. You can try that out.
